### ISSUE TITLE
telegram_bot.py unresponsive after checking version

### ISSUE THREAD

**Issue by chigurg** [Fuyucch1/Vinted-Notifications#3]
after running telegram bot with
`python telegram_bot.py`
the only response is
`You have the latest version!`
after which the program stops responding.

I tried deleting and reinstalling in the \User folder, but same result. 

Any help?

On Windows 10, using PowerShell

**Comment by Fuyucch1** [comment]
Hello there ! 

This is an early WIP and there's no verbose yet. We'll try to find what's going wrong!

1. Can you tell me if the command /hello works in Telegram?
2. Did you add a keyword to the bot? Otherwise, it'll stay in idle

**Comment by chigurg** [comment]
Hi! 
Thanks for the speedy reply!

So, the program was not exitting, didnt give any reponse. Neither did the bot. Command /hello did not work, neither did /add_keyword. 
In the end, I installed the update and tried with a new bot, which got everything running.

I'm testing now with 'nike' as a keyword, but havent gotten any message yet. I'll see if it starts working later, otherwise I'll start a new thread!

**Comment by chigurg** [comment]
.

**Comment by Fuyucch1** [comment]
I'm glad this got fixed by itself!

The bot won't send notifcations for the first batch of items, but it will send them as soon as there are new ones. Just tried for the keyword "nike" and I got a dozen notifications two minutes after setting up the keyword.

It's working properly on my two production environments, but do not hesitate to come back here if you need help!
